- project:
    name: theopenlab/cicd
    check:
      jobs:
        - wordpress-ansible
        - isstreamworking

#- job:
#    name: wordpress-ansible
#    parent: base
#    description: |
#      Create wordpress LAMP stack
#    run: playbooks/wordpress-ansible/run

- job:
    name: isstreamworking
    parent: base
    description: |
      Output to check if stream is working
