- pipeline:
    name: check
    manager: independent
    trigger:
      github:
        - event: pull_request
    success:
      github:
        - status: success
    failure:
      github:
        - status: failure

- project:
    name: theopenlab/cicd
    check:
      jobs:
        - tox-sample
