- project:
    name: theopenlab/cicd
    check:
      jobs:
        - wordpress-ansible

- job:
    name: wordpress-ansible
    parent: base
    description: |
      Create wordpress LAMP stack
    run: playbooks/wordpress-ansible/run

- job:
    name: install-devstack
    parent: base
    description: Install devstack

- job:
    name: isstreamworking
    parent: base
    description: |
      Output to check if stream is working
