- project:
    name: theopenlab/cicd
    check:
      jobs:
        - wordpress-ansible

- job:
    name: wordpress-ansible
    description: |
      Create wordpress LAMP stack
    run: playbooks/wordpress-ansible/run

- job:
    name: isstreamworking
    description: |
      Output to check if stream is working
    run: playbooks/isstreamworking
