---
- name: isstreamworking
  hosts: all
  
  tasks:
    - name: Run for 10 minutes
      shell: |
        for i in `seq 1 100`
        do
          echo 'Checking stream output'
          sleep 6
        done
